### ISSUE TITLE
LTS version

### ISSUE THREAD

**Issue by dvershinin** [ADD-SP/ngx_waf#57]
There have been fast "breaking" releases over time. 

By breaking I mean primarily those which introduced some library dependency (e.g. libinjection), or a program (e.g. flex) during compile time.

Can we have a version line, e.g. 6.x which would be updated with any fixes, but not have "breaking" releases?

E.g. new versions will be released but a specific branch like 6.x would incorporate important fixes, while not having many moving parts.

An example is Varnish Cache. The last version is 6.6.1 (some ABI/breaking changes are OK in there), while the last LTS version is 6.0.8 (all versions 6.0.x are LTS and include only important security/bug fixes).

Background: making RPM packages, but builds of newer versions constantly fail due to "yet another dependency change".

**Comment by ADD-SP** [comment]
Good idea, I've released `v6.1.x` as LTS. Meanwhile, I've explained in the [changelog](https://add-sp.github.io/ngx_waf/changes/lts.html) what the "breaking changes" are.

You can read about the two release flows (LTS and Current) maintained by this project [here](https://add-sp.github.io/ngx_waf/changes/overview.html).

If you have suggestions, let's continue the discussion, otherwise please close this issue.

**Comment by ADD-SP** [comment]
I forgot to mention that branch `lts` corresponds to the LTS version and branch `current` corresponds to the Current version.
